### ISSUE TITLE
Building fail at: Compiling core-graphics v0.3.2

### ISSUE THREAD

**Issue by hasanOryx** [coder543/dataplotlib#15]
I got this error!

>    Compiling core-graphics v0.3.2
> error: type `color_space::__CGColorSpace` is private
>   --> /Users/hasan/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.3.2/src/context.rs:86:26
>    |
> 86 |             let result = CGBitmapContextCreate(ptr::null_mut(),
>    |                          ^^^^^^^^^^^^^^^^^^^^^
> 
> error: type `color_space::__CGColorSpace` is private

**Comment by coder543** [comment]
macOS is not supported, as discussed at greater length here: https://github.com/coder543/dataplotlib/issues/6

That fact has made it so that I basically stopped development on this project awhile ago. I still hope to pick this up again one day and fix all of its problems.
