### ISSUE TITLE
Animated plots

### ISSUE THREAD

**Issue by wgreenberg** [coder543/dataplotlib#16]
Hey, apologies if I'm playing necromancer on this repo, but I'm using it for a personal project and thought I'd contribute the super basic animation support I whipped up today: https://github.com/wgreenberg/dataplotlib/tree/animations

No worries if it's not in the scope/style of the project, but thought I'd letcha know anyhow :)

**Comment by coder543** [comment]
yeah, I lost motivation to work on this repo when I realized that my clever trick to let the graphics be run on a background thread consistently causes it to crash on macOS. I had only been testing on Windows and Linux, but if I were to develop this further, I would want to support macOS too.

It's cool to see that people are still interested in having a plotting library for Rust!
