### ISSUE TITLE
Examples don't build

### ISSUE THREAD

**Issue by shakram02** [coder543/dataplotlib#5]
Hey, I'm glad to have found your project. I tried to build the examples but they didn't want to. It seems like the reason is changing the dependencies in [this](https://github.com/coder543/dataplotlib/commit/09de4a436fe7cef715fa344c373fdbe8b68aaa3d#diff-80398c5faae3c069e4e6aa2ed11b28c0R11) location and using `image` instead of `sdl2`. 

I drilled a little bit and found that `plot_2d` takes 2 arguments one of which is a `Box<Drawable>` for rendering. It isn't supplied in the tests so I thought about opening an issue.

**Comment by coder543** [comment]
Yes, you're correct about where the faulty code change was made. Altering the default feature was something that happened while I was playing with some things, I didn't mean to actually commit that. I have reverted that change here: https://github.com/coder543/dataplotlib/commit/ec43b3f9ba83f15314b02dfa1d580a37868e5516

The examples now compile and run on my computer.

**Comment by coder543** [comment]
and I have now fixed the tests which were failing.

**Comment by shakram02** [comment]
Thanks, that's great. I can contribute in the project if you'd like to. I used rust like 4 months ago (yet a noob) but couldn't use it after that again :cry: - as I didn't have a project to work on -. So if you can bare me as a noob, that'll be so cool
* I'm also a college student so I might not be there all the time but I'll try to get the tasks done on time

**Comment by coder543** [comment]
Yep, if you want to work on making this plotting library useful, there's a list [here](https://github.com/coder543/dataplotlib/issues/2#issuecomment-324477051) of some important things that need to be done! I haven't had much time and energy to spend on this project lately, but it's something the Rust community would benefit from a lot, I think. I'm happy to help you as much as I can, if you try to work on it and get stuck!

I hope I can find time and energy to really pick this project back up again in the next couple of months.

**Comment by shakram02** [comment]
Thank you for offering help, If I get stuck should I leave a comment here? ( or create a new issue?, so anyone can track how the library works -in case that they also want to contribute as they'll probably have the same questions as mine- )

**Comment by coder543** [comment]
Either way works! Whatever you think is appropriate for the question you have. If it's something other people might find useful, an issue could be better.
